### ISSUE TITLE
Support for non steam games 

### ISSUE THREAD

**Issue by Saad-Alareqi** [mcarlucci/decky-storage-cleaner#1]
Hi,
As the title says. Can you add support to non steam games? Only steam games will show up.
Also the games list is so slow to show up even though I had only four steam games. 
Also may I suggest if you can add support to uninstall the non steam game from the storage with all its game files and related files of shader and compatibility data if possible?

If you can add support for non steam games that would be awesome. It's very tiring to uninstall them by searching ids and what not.

**Comment by mcarlucci** [comment]
Hi @Saad-Alareqi, 

Thanks for opening an issue. I introduced an enhancement that adds support for non-steam games. You can track the PR here: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/334
