### ISSUE TITLE
Plugin no longer showing "Never synced to Steam Cloud" warning on Decky 3.0

### ISSUE THREAD

**Issue by cyxceven** [mcarlucci/decky-storage-cleaner#14]
After updating Decky to 3.0, Storage Cleaner has stopped warning me which games have never synced/don't support syncing.

Removing and reinstalling Decky and the plugin has not resolved the issue.

Steam Deck LCD
Steam OS 3.5.19 (Stable build 20240422.1)
Decky 3.0.0
Storage Cleaner v1.3.1

**Comment by eXhumer** [comment]
This issue can be closed as the latest update includes fix.

**Comment by mcarlucci** [comment]
Fixed by #15 and is available in [decky-storage-cleaner 1.4.0](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/706). Thanks again, @eXhumer!
