### ISSUE TITLE
infinite calculation

### ISSUE THREAD

**Issue by FYYR3** [mcarlucci/decky-storage-cleaner#6]
does not work for me, infinite calculation, waited about 15 minutes but no changes.
![16881703358402044243920400017533](https://github.com/mcarlucci/decky-storage-cleaner/assets/138263813/5ae880b8-16cd-4561-85c2-64a5ae9e8e28)

**Comment by mcarlucci** [comment]
Shouldnt take more than 20 seconds to load. If so there is a problem. Some users have reported this in the past and it usually correlates with being low on storage, out of storage or an issue with Decky itself.

Users have reported that a simple Steam Deck restart has resolved the issue. You might try that. If that doesn’t resolve it, let me know.

**Comment by FYYR3** [comment]
I tried restarting steam deck but the problem persists.

**Comment by mcarlucci** [comment]
What version of SteamOS, Decky Loader and Storage Cleaner are you on?

**Comment by FYYR3** [comment]
Steam os 3.4.8
Decky loader 2.10.1
Storage cleaner 1.3.0

**Comment by mcarlucci** [comment]
I’ll try to test on those versions specific versions. You might try reinstalling decky loader in the meantime.

**Comment by mcarlucci** [comment]
> Steam os 3.4.8
> Decky loader 2.10.1
> Storage cleaner 1.3.0

Ok I just tested on these exact versions and there are no problems on my end. I will try to do more testing to be sure. Have you moved shader cache to your SD card by chance? 

I still think reinstalling Decky loader might to the trick, if you are willing to give that a shot.

**Comment by FYYR3** [comment]
after reinstalling decky loader the plugin worked, thanks for the help
