### ISSUE TITLE
Question about appstore API?

### ISSUE THREAD

**Issue by SteveImmanuel** [mcarlucci/decky-storage-cleaner#7]
Hi, really nice plugin, I love it!

Just wondering, in your readme you mentioned that the game names are obtained using `appStore.GetAppOverviewByGameID(game.appid`. Looking at your, I only find the following line without any declaration before:
https://github.com/mcarlucci/decky-storage-cleaner/blob/3515a3a13afd17f6f3bc3213f244cfb963c49b45/src/index.tsx#L83

Can you tell me what does it do and how does it work? Does it call external API or is there any documentation that I can refer to?
I'm curious as to how it obtained the name of non-steam games because as I understand the `appid` of non-steam games are just randomly generated number, I'm not sure though.

**Comment by mcarlucci** [comment]
Check out line 85: https://github.com/mcarlucci/decky-storage-cleaner/blob/3515a3a13afd17f6f3bc3213f244cfb963c49b45/src/index.tsx#L85C1-L85C1

There I am checking if the ‘app_type’ property is equal to ‘1’, which is how steam identifies games under their management.

**Comment by SteveImmanuel** [comment]
Ah yes I understand that part. 
What I'm wondering is how does the `appStore.GetAppOverviewByAppID` retrieve the game name for non-steam games because the ID is just a randomly assigned number, isn't it?

**Comment by mcarlucci** [comment]
You are correct, Steam does randomly assign an id to non-steam games. They also create a game directory named after the id located in `/.steam/steam/steamapps/`
